version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
    ignore:
      # Ignore major version updates for React Native
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']

      # Ignore React Native ecosystem packages (should be updated together with React Native)
      - dependency-name: '@react-native/*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor', 'version-update:semver-patch']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'dependencies'
