version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'npm'
    reviewers:
      - 'your-github-username'
    assignees:
      - 'your-github-username'
    ignore:
      # Ignore major version updates for React Native
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'github-actions'

  # Enable version updates for Gradle (Android)
  - package-ecosystem: 'gradle'
    directory: '/android'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'build'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'android'
    ignore:
      # Ignore Android Gradle Plugin major updates (requires manual intervention)
      - dependency-name: 'com.android.tools.build:gradle'
        update-types: ['version-update:semver-major']

