# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.1.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Build a new Beta Build"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym(scheme: "VodQAReactNative",use_legacy_build_api: true, export_method: "ad-hoc", output_directory: "./build")
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end

