fastlane_version "2.3.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  lane :beta do
    gradle(task: "assembleRelease")
  end
end
