name: Build iOS and Android

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Apps
    uses: ./.github/workflows/build-apps.yml
    with:
      upload_release_artifacts: false
      upload_pr_artifacts: true
